// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { ModelSelectionScope } from "./ModelSelectionScope";
import type { ProviderId } from "./ProviderId";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * Persisted active provider/model selection at a global, workspace, or thread scope.
 */
export type ActiveModelSelection = { scope: ModelSelectionScope, workspace_id: WorkspaceId | null, thread_id: ThreadId | null, provider_id: ProviderId, model_id: ModelId, provider_name: string, model_name: string, updated_at: string, };
