// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level lifecycle status of an agent run.
 */
export type AgentRunStatus = "Queued" | "Running" | "WaitingApproval" | "Paused" | "Cancelled" | "Failed" | "Completed";
