// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { AgentRunStatus } from "./AgentRunStatus";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A single agent run inside a workspace and thread.
 */
export type AgentRun = { 
/**
 * Run identifier.
 */
id: AgentRunId, 
/**
 * Thread the run belongs to.
 */
thread_id: ThreadId, 
/**
 * Workspace the run belongs to.
 */
workspace_id: WorkspaceId, 
/**
 * Current lifecycle status.
 */
status: AgentRunStatus, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Timestamp when the run started running.
 */
started_at: string | null, 
/**
 * Timestamp when the run finished.
 */
completed_at: string | null, };
