// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionScope } from "./PermissionScope";

/**
 * Definition of an agent that can be registered with the orchestrator.
 */
export type AgentDefinition = { 
/**
 * Machine-readable agent name.
 */
name: string, 
/**
 * Human-readable description.
 */
description: string, 
/**
 * System instructions provided to the agent.
 */
system_instructions: string, 
/**
 * Names of tools the agent is allowed to use.
 */
allowed_tools: Array<string>, 
/**
 * Default model selection policy.
 */
default_model_policy: string, 
/**
 * Default permission scope for the agent.
 */
default_permission_scope: PermissionScope, };
