// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Product-level error type returned by Portico APIs.
 */
export type AppError = { "NotFound": { 
/**
 * Description of the missing resource.
 */
resource: string, } } | { "PermissionDenied": { 
/**
 * Human-readable reason for the denial.
 */
reason: string, } } | { "Internal": { 
/**
 * Error message.
 */
message: string, } };
