// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { ApprovalRequestId } from "./ApprovalRequestId";
import type { ApprovalRequestStatus } from "./ApprovalRequestStatus";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A request for user approval of an action.
 */
export type ApprovalRequest = { 
/**
 * Database row id.
 */
id: ApprovalRequestId, 
/**
 * Run that requested approval.
 */
run_id: AgentRunId, 
/**
 * Workspace that owns the run.
 */
workspace_id: WorkspaceId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Action being requested.
 */
action: string, 
/**
 * Resource the action targets.
 */
resource: string, 
/**
 * Current status.
 */
status: ApprovalRequestStatus, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Resolution timestamp.
 */
resolved_at: string | null, 
/**
 * Optional reason provided when the request was denied.
 */
resolution_reason: string | null, };
