// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of an approval request.
 */
export type ApprovalRequestStatus = "Pending" | "Approved" | "Denied";
