// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preview of an artifact file suitable for frontend rendering.
 */
export type ArtifactPreview = { 
/**
 * Original filesystem path.
 */
path: string, 
/**
 * Detected MIME type.
 */
mime_type: string, 
/**
 * File contents encoded as base64.
 */
content_base64: string, 
/**
 * File size in bytes.
 */
size_bytes: bigint, };
