// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationId } from "./AutomationId";
import type { AutomationTrigger } from "./AutomationTrigger";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A user-defined automation rule.
 */
export type Automation = { 
/**
 * Automation identifier.
 */
id: AutomationId, 
/**
 * Owning workspace.
 */
workspace_id: WorkspaceId, 
/**
 * Display name.
 */
name: string, 
/**
 * Human-readable description.
 */
description: string, 
/**
 * Trigger kind.
 */
trigger: AutomationTrigger, 
/**
 * Cron expression for scheduled triggers.
 */
cron_expr: string | null, 
/**
 * Whether the automation is currently enabled.
 */
enabled: boolean, 
/**
 * Permission policy configuration.
 */
permission_policy: any, 
/**
 * Next scheduled run time.
 */
next_run_at: string | null, 
/**
 * Last time the automation ran.
 */
last_run_at: string | null, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Last update timestamp.
 */
updated_at: string, };
