// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trigger that can activate an automation.
 */
export type AutomationTrigger = "Scheduled" | "FileChange" | "GitEvent" | "ManualRoutine" | "WebhookReserved" | "ThreadWakeup";
