// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { BackgroundTaskId } from "./BackgroundTaskId";
import type { BackgroundTaskStatus } from "./BackgroundTaskStatus";
import type { TaskKind } from "./TaskKind";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A unit of background work queued for asynchronous execution.
 */
export type BackgroundTask = { 
/**
 * Task identifier.
 */
id: BackgroundTaskId, 
/**
 * Owning workspace.
 */
workspace_id: WorkspaceId, 
/**
 * Optional owning thread.
 */
thread_id: ThreadId | null, 
/**
 * Optional owning run.
 */
run_id: AgentRunId | null, 
/**
 * Kind of work to perform.
 */
task_kind: TaskKind, 
/**
 * Opaque task payload.
 */
payload: any, 
/**
 * Current lifecycle status.
 */
status: BackgroundTaskStatus, 
/**
 * Higher values are processed first.
 */
priority: bigint, 
/**
 * Number of processing attempts so far.
 */
attempts: number, 
/**
 * Maximum number of attempts before marking failed.
 */
max_attempts: number, 
/**
 * Earliest time the task should be processed.
 */
scheduled_at: string, 
/**
 * Timestamp when the task was leased.
 */
leased_at: string | null, 
/**
 * Worker identifier that currently holds the lease.
 */
leased_by: string | null, 
/**
 * Earliest time a failed task should be retried.
 */
next_retry_at: string | null, 
/**
 * Last error message if the task failed.
 */
error_message: string | null, 
/**
 * Short summary of the task result.
 */
result_summary: string | null, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Last update timestamp.
 */
updated_at: string, };
