// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for an in-app browser window.
 */
export type BrowserWindowId = string;
