// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action executed inside an in-app browser window.
 */
export type BrowserAction = { "kind": "Click", 
/**
 * CSS selector for the target element.
 */
selector: string, } | { "kind": "Type", 
/**
 * CSS selector for the target input.
 */
selector: string, 
/**
 * Text to type.
 */
text: string, } | { "kind": "ExtractVisibleText" } | { "kind": "Wait", 
/**
 * Duration to wait.
 */
ms: bigint, } | { "kind": "Screenshot" };
