// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserWindowId } from "./BrowserWindowId";

/**
 * Metadata describing an open in-app browser window.
 */
export type BrowserWindowInfo = { 
/**
 * Window identifier.
 */
id: BrowserWindowId, 
/**
 * Currently loaded URL.
 */
url: string, 
/**
 * Window title.
 */
title: string, };
