// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Built-in agent roles available to the orchestrator.
 */
export type BuiltInAgent = "Default" | "Explorer" | "Planner" | "Worker" | "Reviewer" | "SecurityReviewer" | "Tester" | "Researcher" | "DocWriter";
