// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasId } from "./CanvasId";
import type { CanvasNodeId } from "./CanvasNodeId";
import type { CanvasNodeKind } from "./CanvasNodeKind";
import type { CanvasNodeSource } from "./CanvasNodeSource";
import type { CanvasNodeStatus } from "./CanvasNodeStatus";

/**
 * One node on a canvas.
 */
export type CanvasNode = { id: CanvasNodeId, canvas_id: CanvasId, kind: CanvasNodeKind, title: string, summary: string, status: CanvasNodeStatus, parent_id: CanvasNodeId | null, position_x: number, position_y: number, layout_rank: bigint, source: CanvasNodeSource, 
/**
 * Kind-specific JSON payload (insight links, stage launch hints, …).
 */
payload_json: string, created_at: string, updated_at: string, };
