// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic kind of a canvas edge.
 */
export type CanvasEdgeKind = "Parent" | "Related" | "DerivedFrom" | "Blocks";
