// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasId } from "./CanvasId";
import type { CanvasKind } from "./CanvasKind";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * Durable mind-map document for a project or thread.
 */
export type Canvas = { id: CanvasId, workspace_id: WorkspaceId, 
/**
 * Set when `kind == Thread`.
 */
thread_id: ThreadId | null, title: string, kind: CanvasKind, 
/**
 * JSON: `{ "x": number, "y": number, "zoom": number }`.
 */
viewport_json: string, revision: bigint, last_extracted_at: string | null, created_at: string, updated_at: string, };
