// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasEdgeId } from "./CanvasEdgeId";
import type { CanvasEdgeKind } from "./CanvasEdgeKind";
import type { CanvasId } from "./CanvasId";
import type { CanvasNodeId } from "./CanvasNodeId";

/**
 * Directed edge between canvas nodes.
 */
export type CanvasEdge = { id: CanvasEdgeId, canvas_id: CanvasId, from_id: CanvasNodeId, to_id: CanvasNodeId, kind: CanvasEdgeKind, label: string | null, created_at: string, };
