// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Canvas } from "./Canvas";
import type { CanvasEdge } from "./CanvasEdge";
import type { CanvasLink } from "./CanvasLink";
import type { CanvasNode } from "./CanvasNode";

/**
 * Full graph snapshot for the canvas UI.
 */
export type CanvasSnapshot = { canvas: Canvas, nodes: Array<CanvasNode>, edges: Array<CanvasEdge>, links: Array<CanvasLink>, };
