// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a goal/stage (insights use Todo/Done loosely).
 */
export type CanvasNodeStatus = "Todo" | "InProgress" | "Done" | "Blocked" | "Stale";
