// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who created or last owned the node content.
 */
export type CanvasNodeSource = "Auto" | "User" | "Agent";
