// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Existing product entity referenced by a canvas node.
 */
export type CanvasLinkRefType = "Thread" | "Message" | "Run" | "Orchestration";
