// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasLinkId } from "./CanvasLinkId";
import type { CanvasLinkRefType } from "./CanvasLinkRefType";
import type { CanvasNodeId } from "./CanvasNodeId";

/**
 * Link from a canvas node to a durable product entity.
 */
export type CanvasLink = { id: CanvasLinkId, node_id: CanvasNodeId, ref_type: CanvasLinkRefType, ref_id: string, snippet: string | null, created_at: string, };
