// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { InstructionFile } from "./InstructionFile";
import type { MemoryItem } from "./MemoryItem";
import type { RagChunk } from "./RagChunk";
import type { ThreadId } from "./ThreadId";

/**
 * Summary of everything assembled for a run's prompt context.
 */
export type ContextSummary = { run_id: AgentRunId, thread_id: ThreadId, instructions: Array<InstructionFile>, memories: Array<MemoryItem>, rag_chunks: Array<RagChunk>, estimated_tokens: bigint, privacy_flags: Array<string>, };
