// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A captured desktop screenshot encoded as a PNG.
 */
export type DesktopCapture = { 
/**
 * PNG image encoded as base64.
 */
image_base64: string, 
/**
 * Image width in pixels.
 */
width: number, 
/**
 * Image height in pixels.
 */
height: number, };
