// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticsBundleId } from "./DiagnosticsBundleId";

/**
 * A redacted diagnostics bundle collected for support or debugging.
 */
export type DiagnosticsBundle = { 
/**
 * Bundle identifier.
 */
id: DiagnosticsBundleId, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Path to the copied log file inside the bundle.
 */
log_path: string, 
/**
 * Path to the redacted audit summary inside the bundle.
 */
audit_summary_path: string, 
/**
 * Application version at the time the bundle was created.
 */
app_version: string, 
/**
 * Operating system information.
 */
os_info: string, 
/**
 * Whether secrets were redacted from the bundle contents.
 */
redacted: boolean, 
/**
 * Total size of the bundle directory in bytes.
 */
size_bytes: bigint, };
