// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * Authoritative product context attached to every capability execution.
 *
 * Callers must obtain this from the runtime using a persisted run id. Trust,
 * ownership, roots, and allowed paths are snapshots of backend-owned state and
 * must never be accepted from a frontend or model payload.
 */
export type ExecutionContext = { 
/**
 * Run requesting the capability.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Workspace that owns the thread and run.
 */
workspace_id: WorkspaceId, 
/**
 * Canonical workspace root at preparation time.
 */
canonical_workspace_root: string, 
/**
 * Persisted trust state at preparation time.
 */
trusted_workspace: boolean, 
/**
 * Canonical paths explicitly granted for reads.
 */
allowed_read_paths: Array<string>, 
/**
 * Canonical paths explicitly granted for writes.
 */
allowed_write_paths: Array<string>, 
/**
 * Workspace update timestamp used as the trust/config revision.
 */
trust_revision: string, 
/**
 * Correlation id shared by policy, approval, execution, and audit records.
 */
correlation_id: string, };
