// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend-authoritative product capability probe (single source of truth for UI).
 */
export type FeatureCapabilities = { 
/**
 * Durable single-agent conversation + safe tools + approval recovery.
 */
core_agent_workflow: boolean, 
/**
 * Multi-role orchestration secondary path (durable sessions).
 */
multi_agent_orchestration: boolean, 
/**
 * Project instructions, non-sensitive memory, and RAG enter the agent prompt.
 */
context_injection: boolean, 
/**
 * Workspace disk scan / rebuild for RAG.
 */
workspace_indexer: boolean, 
/**
 * Search + structured edit tools in the durable tool allowlist.
 */
advanced_file_tools: boolean, 
/**
 * Skill invocation inside agent runs (list-only when false).
 */
skill_invocation: boolean, 
/**
 * Native browser/desktop automation.
 */
native_automation: boolean, 
/**
 * MCP servers attached to agent tool loop.
 */
mcp_agent_tools: boolean, 
/**
 * Terminal / shell execution.
 */
terminal: boolean, 
/**
 * Git mutation (stage/commit/push).
 */
git_mutation: boolean, 
/**
 * Scheduled automations (UI + IPC).
 */
automations: boolean, 
/**
 * Human-readable notes for disabled surfaces.
 */
notes: Array<string>, };
