// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A loaded instruction file (e.g. `AGENTS.md`).
 */
export type InstructionFile = { path: string, content: string, scope: string, };
