// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpTransport } from "./McpTransport";

/**
 * Persisted configuration for an MCP server.
 */
export type McpServerConfig = { 
/**
 * Database row id.
 */
id: bigint, 
/**
 * Human-readable name.
 */
name: string, 
/**
 * Transport protocol.
 */
transport: McpTransport, 
/**
 * Command to execute for stdio transport.
 */
command: string | null, 
/**
 * Arguments for the command.
 */
args: Array<string>, 
/**
 * URL for HTTP transport.
 */
url: string | null, 
/**
 * Environment variables for the server process.
 */
env: { [key in string]?: string }, 
/**
 * Whether the server is enabled.
 */
enabled: boolean, };
