// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport protocol used to communicate with an MCP server.
 */
export type McpTransport = "Stdio" | "Http";
