// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryId } from "./MemoryId";
import type { MemoryScope } from "./MemoryScope";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A single persisted memory entry.
 */
export type MemoryItem = { id: MemoryId, scope: MemoryScope, workspace_id: WorkspaceId | null, thread_id: ThreadId | null, key: string, value: string, sensitive: boolean, created_at: string, updated_at: string, };
