// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The author role of a durable conversation message.
 */
export type MessageRole = "User" | "Assistant" | "System";
