// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { MessageId } from "./MessageId";
import type { MessageRole } from "./MessageRole";
import type { ThreadId } from "./ThreadId";

/**
 * A durable entry in a thread conversation.
 */
export type Message = { id: MessageId, thread_id: ThreadId, run_id: AgentRunId | null, role: MessageRole, content: string, client_request_id: string | null, created_at: string, };
