// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tracked database migration applied by sqlx.
 */
export type MigrationInfo = { 
/**
 * Migration version number.
 */
version: bigint, 
/**
 * Migration name / description.
 */
name: string, 
/**
 * Timestamp when the migration was applied.
 */
applied_at: string, 
/**
 * Migration checksum.
 */
checksum: string, };
