// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope that owns an active provider/model selection.
 */
export type ModelSelectionScope = "Global" | "Workspace" | "Thread";
