// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelCapability } from "./ModelCapability";
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";

/**
 * Model definition registered under a provider.
 */
export type ModelInfo = { id: ModelId, provider_id: ProviderId, provider_name: string, model_name: string, display_name: string, capabilities: ModelCapability, };
