// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capability matrix for a specific model.
 */
export type ModelCapability = { supports_streaming: boolean, supports_tools: boolean, supports_json_schema: boolean, supports_vision: boolean, supports_pdf: boolean, supports_system_prompt: boolean, supports_embeddings: boolean, max_context_tokens: bigint | null, input_price_per_1k: number | null, output_price_per_1k: number | null, };
