// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category of a user-facing notification.
 */
export type NotificationCategory = "System" | "InApp" | "ApprovalRequired" | "TaskCompleted";
