// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { NotificationCategory } from "./NotificationCategory";
import type { NotificationId } from "./NotificationId";
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A user-facing notification persisted in the notification center.
 */
export type Notification = { 
/**
 * Notification identifier.
 */
id: NotificationId, 
/**
 * Owning workspace.
 */
workspace_id: WorkspaceId, 
/**
 * Optional owning thread.
 */
thread_id: ThreadId | null, 
/**
 * Optional owning run.
 */
run_id: AgentRunId | null, 
/**
 * Notification title.
 */
title: string, 
/**
 * Notification body.
 */
body: string, 
/**
 * Notification category.
 */
category: NotificationCategory, 
/**
 * Whether the notification has been read.
 */
read: boolean, 
/**
 * Creation timestamp.
 */
created_at: string, };
