// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a multi-agent orchestration session.
 */
export type OrchestrationStatus = "Planning" | "Running" | "Completed" | "Failed" | "Cancelled";
