// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { SubagentRun } from "./SubagentRun";

/**
 * A plan describing the subagents to run for a parent run.
 */
export type OrchestrationPlan = { 
/**
 * Parent run the plan belongs to.
 */
parent_run_id: AgentRunId, 
/**
 * Subagents to execute.
 */
subagents: Array<SubagentRun>, };
