// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { OrchestrationId } from "./OrchestrationId";
import type { OrchestrationPlan } from "./OrchestrationPlan";
import type { OrchestrationStatus } from "./OrchestrationStatus";
import type { ThreadId } from "./ThreadId";
import type { WorkflowPatternId } from "./WorkflowPatternId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * Durable multi-agent orchestration session.
 */
export type Orchestration = { id: OrchestrationId, parent_run_id: AgentRunId, workspace_id: WorkspaceId, thread_id: ThreadId, task: string, status: OrchestrationStatus, plan: OrchestrationPlan, pattern_ids: Array<WorkflowPatternId>, result_summary: string | null, created_at: string, updated_at: string, completed_at: string | null, };
