// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowPatternId } from "./WorkflowPatternId";

/**
 * Lightweight pattern hint returned across module boundaries (no storage coupling).
 */
export type PatternHint = { id: WorkflowPatternId, name: string, summary: string, preferred_roles: Array<string>, collaboration_style: string, strength: number, score: number, };
