// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginId } from "./PluginId";
import type { PluginPermissions } from "./PluginPermissions";

/**
 * Manifest describing an installed Portico plugin.
 */
export type PluginManifest = { 
/**
 * Plugin identifier.
 */
id: PluginId, 
/**
 * Short machine-readable name.
 */
name: string, 
/**
 * Semantic version.
 */
version: string, 
/**
 * Human-readable display name.
 */
display_name: string, 
/**
 * Long-form description.
 */
description: string, 
/**
 * Names of skills advertised by the plugin.
 */
skills: Array<string>, 
/**
 * Names of tools provided by the plugin.
 */
tools: Array<string>, 
/**
 * Declared permissions.
 */
permissions: PluginPermissions, 
/**
 * Whether the plugin is currently enabled.
 */
enabled: boolean, 
/**
 * Timestamp when the plugin was installed.
 */
installed_at: string, };
