// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A host capability implemented by a plugin.
 */
export type PluginCapability = "markdown.preview" | "markdown.export.html" | "markdown.export.docx" | "markdown.export.pdf";
