// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permissions declared by a plugin at install time.
 */
export type PluginPermissions = { 
/**
 * Host patterns the plugin is allowed to access over the network.
 */
network: Array<string>, 
/**
 * Filesystem access level: `"none"`, `"read"`, or `"write"`.
 */
filesystem: string, };
