// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the most recent bounded provider health check.
 */
export type ProviderHealthStatus = "Checking" | "Ready" | "Degraded" | "InvalidCredentials" | "Unsupported";
