// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for a model provider configuration.
 */
export type ProviderId = string;
