// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";
import type { ProviderHealthStatus } from "./ProviderHealthStatus";
import type { ProviderId } from "./ProviderId";

/**
 * Safe, persisted provider health summary. It never contains credentials or raw responses.
 */
export type ProviderHealth = { provider_id: ProviderId, model_id: ModelId, status: ProviderHealthStatus, error_code: string | null, message: string | null, checked_at: string, };
