// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderId } from "./ProviderId";
import type { ProviderKind } from "./ProviderKind";
import type { RetryPolicy } from "./RetryPolicy";

/**
 * Persisted configuration for a model provider.
 */
export type ProviderConfig = { id: ProviderId, kind: ProviderKind, display_name: string, base_url: string | null, api_key_reference: string, organization_id: string | null, project_id: string | null, default_headers: { [key in string]?: string }, timeout_ms: bigint, retry_policy: RetryPolicy, fallback_provider_ids: Array<ProviderId>, enabled: boolean, created_at: string, updated_at: string, };
