// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported provider backends.
 */
export type ProviderKind = "OpenAI" | "Anthropic" | "DeepSeek" | "Google" | "Groq" | "OpenRouter" | "AzureOpenAI" | "Ollama" | "Custom";
