// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chunk retrieved from the RAG vector index.
 */
export type RagChunk = { id: bigint, document_path: string, chunk_index: number, content: string, score: number, };
