// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retry policy for provider API calls.
 */
export type RetryPolicy = { max_retries: number, initial_backoff_ms: bigint, max_backoff_ms: bigint, };
