// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { ThreadId } from "./ThreadId";

/**
 * A persisted event in a run's timeline.
 */
export type RunEvent = { 
/**
 * Database row id.
 */
id: bigint, 
/**
 * Run the event belongs to.
 */
run_id: AgentRunId, 
/**
 * Thread the event belongs to.
 */
thread_id: ThreadId, 
/**
 * Sequence order inside the run.
 */
sequence: bigint, 
/**
 * Event type tag.
 */
event_type: string, 
/**
 * Structured payload.
 */
payload: any, 
/**
 * Creation timestamp.
 */
created_at: string, };
