// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";

/**
 * Immutable provider/model configuration captured for a run before network execution.
 */
export type RunModelSnapshot = { run_id: AgentRunId, provider_id: ProviderId, model_id: ModelId, provider_name: string, model_name: string, provider_config_updated_at: string, created_at: string, };
