// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginId } from "./PluginId";
import type { SkillId } from "./SkillId";

/**
 * A skill exposed by a plugin.
 */
export type Skill = { 
/**
 * Skill identifier.
 */
id: SkillId, 
/**
 * Owning plugin.
 */
plugin_id: PluginId, 
/**
 * Short machine-readable name.
 */
name: string, 
/**
 * Human-readable description.
 */
description: string, 
/**
 * Description used to match natural-language triggers.
 */
trigger_description: string, 
/**
 * Optional path to an instruction file bundled with the plugin.
 */
instruction_file: string | null, 
/**
 * Names of tools the skill requires.
 */
required_tools: Array<string>, };
