// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { AgentRunStatus } from "./AgentRunStatus";

/**
 * A single subagent run managed by the orchestrator.
 */
export type SubagentRun = { 
/**
 * Subagent run identifier.
 */
id: AgentRunId, 
/**
 * Parent run that owns this subagent.
 */
parent_run_id: AgentRunId, 
/**
 * Name of the agent definition used.
 */
agent_name: string, 
/**
 * Current lifecycle status.
 */
status: AgentRunStatus, 
/**
 * Task description passed to the subagent.
 */
task_description: string, 
/**
 * Short summary of the subagent output.
 */
output_summary: string | null, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Completion timestamp.
 */
completed_at: string | null, };
