// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of work a background task represents.
 */
export type TaskKind = "AgentRun" | "Routine" | "ThreadWakeup" | "ScheduledJob";
