// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of a terminal command execution.
 */
export type TerminalOutput = { 
/**
 * Standard output captured from the command.
 */
stdout: string, 
/**
 * Standard error captured from the command.
 */
stderr: string, 
/**
 * Process exit code, if the process exited.
 */
exit_code: number | null, };
