// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A conversation thread inside a workspace.
 */
export type Thread = { 
/**
 * Thread identifier.
 */
id: ThreadId, 
/**
 * Owning workspace.
 */
workspace_id: WorkspaceId, 
/**
 * Display title.
 */
title: string, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Last update timestamp.
 */
updated_at: string, };
