// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A conversation thread inside a workspace.
 */
export type Thread = { 
/**
 * Thread identifier.
 */
id: ThreadId, 
/**
 * Owning workspace.
 */
workspace_id: WorkspaceId, 
/**
 * Display title.
 */
title: string, 
/**
 * When set, this session was branched from another session (mind-map edge).
 */
parent_thread_id: ThreadId | null, 
/**
 * When set, the session is in the archive (hidden from the active list).
 * Rows older than 30 days are permanently purged.
 */
archived_at: string | null, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Last update timestamp.
 */
updated_at: string, };
