// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { ApprovalRequestId } from "./ApprovalRequestId";
import type { ThreadId } from "./ThreadId";
import type { ToolInvocationId } from "./ToolInvocationId";
import type { ToolInvocationStatus } from "./ToolInvocationStatus";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * Immutable prepared request plus its durable execution receipt.
 */
export type ToolInvocation = { 
/**
 * Stable invocation identifier.
 */
id: ToolInvocationId, 
/**
 * Owning run.
 */
run_id: AgentRunId, 
/**
 * Owning thread.
 */
thread_id: ThreadId, 
/**
 * Owning workspace.
 */
workspace_id: WorkspaceId, 
/**
 * Provider/model tool-call id. Unique within a run when supplied.
 */
model_call_id: string | null, 
/**
 * Product tool name.
 */
tool_name: string, 
/**
 * Tool implementation/version snapshot.
 */
tool_version: string, 
/**
 * Policy action, such as `filesystem.read` or `filesystem.write`.
 */
action: string, 
/**
 * Canonical, human-readable resource summary.
 */
resource: string, 
/**
 * Immutable validated arguments.
 */
arguments: any, 
/**
 * SHA-256 fingerprint over context, tool metadata, and canonical arguments.
 */
request_hash: string, 
/**
 * Version of the policy that produced the decision.
 */
policy_version: string, 
/**
 * Workspace trust/config revision bound into the approval decision.
 */
context_revision: string, 
/**
 * Current durable state.
 */
status: ToolInvocationStatus, 
/**
 * Linked approval request for `WaitingApproval` invocations.
 */
approval_request_id: ApprovalRequestId | null, 
/**
 * Successful durable result.
 */
result: any, 
/**
 * Safe failure summary.
 */
error: string | null, 
/**
 * Opaque recovery metadata such as file pre/post hashes.
 */
recovery: any, 
/**
 * Worker lease token while executing.
 */
lease_token: string | null, 
/**
 * Number of successful claims.
 */
attempts: number, 
/**
 * Cancellation requested after execution had already been claimed.
 */
cancel_requested: boolean, 
/**
 * Correlation id propagated from [`ExecutionContext`].
 */
correlation_id: string, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Last durable state update.
 */
updated_at: string, 
/**
 * First execution claim timestamp.
 */
started_at: string | null, 
/**
 * Terminal completion timestamp.
 */
completed_at: string | null, };
