// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable lifecycle for one prepared tool side effect.
 */
export type ToolInvocationStatus = "Ready" | "WaitingApproval" | "Approved" | "Executing" | "Succeeded" | "Failed" | "Denied" | "Cancelled" | "NeedsReconciliation";
