// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App-level usage budget guard.
 */
export type UsageBudget = { per_run_usd: number | null, daily_usd: number | null, };
