// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";
import type { ModelId } from "./ModelId";
import type { ProviderId } from "./ProviderId";

/**
 * Recorded LLM usage for a single run/model call.
 */
export type UsageRecord = { id: bigint, run_id: AgentRunId, provider_id: ProviderId, model_id: ModelId, input_tokens: bigint, output_tokens: bigint, cost_usd: number, created_at: string, };
