// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";
import type { WorkspaceId } from "./WorkspaceId";
import type { WorktreeId } from "./WorktreeId";

/**
 * A checked-out worktree linked to a workspace and thread.
 */
export type Worktree = { 
/**
 * Worktree identifier.
 */
id: WorktreeId, 
/**
 * Owning workspace.
 */
workspace_id: WorkspaceId, 
/**
 * Owning thread.
 */
thread_id: ThreadId, 
/**
 * Display name.
 */
name: string, 
/**
 * Filesystem path.
 */
path: string, 
/**
 * Creation timestamp.
 */
created_at: string, };
