// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle status of a workflow pattern.
 */
export type WorkflowPatternStatus = "Active" | "Suggested" | "Muted";
