// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryScope } from "./MemoryScope";
import type { WorkflowPatternId } from "./WorkflowPatternId";
import type { WorkflowPatternStatus } from "./WorkflowPatternStatus";
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A durable user/workspace work habit used to condition multi-agent planning.
 *
 * Patterns are owned by the memory layer. Orchestration only consumes DTO-like
 * hints through ports so the two modules can evolve independently.
 */
export type WorkflowPattern = { id: WorkflowPatternId, scope: MemoryScope, workspace_id: WorkspaceId | null, name: string, summary: string, 
/**
 * Free-text triggers matched during recall (keywords, phrases).
 */
trigger_text: string, 
/**
 * Preferred agent role names, ordered.
 */
preferred_roles: Array<string>, collaboration_style: string, strength: number, success_count: bigint, failure_count: bigint, last_used_at: string | null, status: WorkflowPatternStatus, created_at: string, updated_at: string, };
