// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceId } from "./WorkspaceId";

/**
 * A user workspace.
 */
export type Workspace = { 
/**
 * Workspace identifier.
 */
id: WorkspaceId, 
/**
 * Display name.
 */
name: string, 
/**
 * Root directory path.
 */
root_path: string, 
/**
 * Whether the workspace is trusted for sensitive operations.
 */
trusted: boolean, 
/**
 * Paths explicitly allowed for read access.
 */
allowed_read_paths: Array<string>, 
/**
 * Paths explicitly allowed for write access.
 */
allowed_write_paths: Array<string>, 
/**
 * Creation timestamp.
 */
created_at: string, 
/**
 * Last update timestamp.
 */
updated_at: string, };
