/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as DesktopIndexRouteImport } from './routes/desktop/index'
import { Route as BrowserIndexRouteImport } from './routes/browser/index'
import { Route as AutomationsIndexRouteImport } from './routes/automations/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces/$workspaceId/index'
import { Route as WorkspacesWorkspaceIdMemoryIndexRouteImport } from './routes/workspaces/$workspaceId/memory/index'
import { Route as WorkspacesWorkspaceIdGitIndexRouteImport } from './routes/workspaces/$workspaceId/git/index'
import { Route as WorkspacesWorkspaceIdThreadsThreadIdIndexRouteImport } from './routes/workspaces/$workspaceId/threads/$threadId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopIndexRoute = DesktopIndexRouteImport.update({
  id: '/desktop/',
  path: '/desktop/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserIndexRoute = BrowserIndexRouteImport.update({
  id: '/browser/',
  path: '/browser/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdMemoryIndexRoute =
  WorkspacesWorkspaceIdMemoryIndexRouteImport.update({
    id: '/workspaces/$workspaceId/memory/',
    path: '/workspaces/$workspaceId/memory/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdGitIndexRoute =
  WorkspacesWorkspaceIdGitIndexRouteImport.update({
    id: '/workspaces/$workspaceId/git/',
    path: '/workspaces/$workspaceId/git/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdThreadsThreadIdIndexRoute =
  WorkspacesWorkspaceIdThreadsThreadIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/threads/$threadId/',
    path: '/workspaces/$workspaceId/threads/$threadId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit/': typeof AuditIndexRoute
  '/automations/': typeof AutomationsIndexRoute
  '/browser/': typeof BrowserIndexRoute
  '/desktop/': typeof DesktopIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/git/': typeof WorkspacesWorkspaceIdGitIndexRoute
  '/workspaces/$workspaceId/memory/': typeof WorkspacesWorkspaceIdMemoryIndexRoute
  '/workspaces/$workspaceId/threads/$threadId/': typeof WorkspacesWorkspaceIdThreadsThreadIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditIndexRoute
  '/automations': typeof AutomationsIndexRoute
  '/browser': typeof BrowserIndexRoute
  '/desktop': typeof DesktopIndexRoute
  '/models': typeof ModelsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/git': typeof WorkspacesWorkspaceIdGitIndexRoute
  '/workspaces/$workspaceId/memory': typeof WorkspacesWorkspaceIdMemoryIndexRoute
  '/workspaces/$workspaceId/threads/$threadId': typeof WorkspacesWorkspaceIdThreadsThreadIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit/': typeof AuditIndexRoute
  '/automations/': typeof AutomationsIndexRoute
  '/browser/': typeof BrowserIndexRoute
  '/desktop/': typeof DesktopIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/git/': typeof WorkspacesWorkspaceIdGitIndexRoute
  '/workspaces/$workspaceId/memory/': typeof WorkspacesWorkspaceIdMemoryIndexRoute
  '/workspaces/$workspaceId/threads/$threadId/': typeof WorkspacesWorkspaceIdThreadsThreadIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit/'
    | '/automations/'
    | '/browser/'
    | '/desktop/'
    | '/models/'
    | '/plugins/'
    | '/settings/'
    | '/skills/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/git/'
    | '/workspaces/$workspaceId/memory/'
    | '/workspaces/$workspaceId/threads/$threadId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/automations'
    | '/browser'
    | '/desktop'
    | '/models'
    | '/plugins'
    | '/settings'
    | '/skills'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/git'
    | '/workspaces/$workspaceId/memory'
    | '/workspaces/$workspaceId/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/audit/'
    | '/automations/'
    | '/browser/'
    | '/desktop/'
    | '/models/'
    | '/plugins/'
    | '/settings/'
    | '/skills/'
    | '/workspaces/'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/git/'
    | '/workspaces/$workspaceId/memory/'
    | '/workspaces/$workspaceId/threads/$threadId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  BrowserIndexRoute: typeof BrowserIndexRoute
  DesktopIndexRoute: typeof DesktopIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
  WorkspacesWorkspaceIdGitIndexRoute: typeof WorkspacesWorkspaceIdGitIndexRoute
  WorkspacesWorkspaceIdMemoryIndexRoute: typeof WorkspacesWorkspaceIdMemoryIndexRoute
  WorkspacesWorkspaceIdThreadsThreadIdIndexRoute: typeof WorkspacesWorkspaceIdThreadsThreadIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/': {
      id: '/desktop/'
      path: '/desktop'
      fullPath: '/desktop/'
      preLoaderRoute: typeof DesktopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser/': {
      id: '/browser/'
      path: '/browser'
      fullPath: '/browser/'
      preLoaderRoute: typeof BrowserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/': {
      id: '/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/memory/': {
      id: '/workspaces/$workspaceId/memory/'
      path: '/workspaces/$workspaceId/memory'
      fullPath: '/workspaces/$workspaceId/memory/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdMemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/git/': {
      id: '/workspaces/$workspaceId/git/'
      path: '/workspaces/$workspaceId/git'
      fullPath: '/workspaces/$workspaceId/git/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdGitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/threads/$threadId/': {
      id: '/workspaces/$workspaceId/threads/$threadId/'
      path: '/workspaces/$workspaceId/threads/$threadId'
      fullPath: '/workspaces/$workspaceId/threads/$threadId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdThreadsThreadIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  AutomationsIndexRoute: AutomationsIndexRoute,
  BrowserIndexRoute: BrowserIndexRoute,
  DesktopIndexRoute: DesktopIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
  WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
  WorkspacesWorkspaceIdGitIndexRoute: WorkspacesWorkspaceIdGitIndexRoute,
  WorkspacesWorkspaceIdMemoryIndexRoute: WorkspacesWorkspaceIdMemoryIndexRoute,
  WorkspacesWorkspaceIdThreadsThreadIdIndexRoute:
    WorkspacesWorkspaceIdThreadsThreadIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
