// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunId } from "./AgentRunId";

/**
 * An artifact produced by an agent run.
 */
export type Artifact = { 
/**
 * Database row id.
 */
id: bigint, 
/**
 * Run that produced the artifact.
 */
run_id: AgentRunId, 
/**
 * Artifact name.
 */
name: string, 
/**
 * MIME type.
 */
mime_type: string, 
/**
 * Optional filesystem path.
 */
path: string | null, 
/**
 * Optional content preview.
 */
content_preview: string | null, };
