// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRun } from "./AgentRun";
import type { AgentRunId } from "./AgentRunId";
import type { AgentRunStatus } from "./AgentRunStatus";
import type { Artifact } from "./Artifact";
import type { ThreadId } from "./ThreadId";

/**
 * Events emitted by the Portico runtime to subscribers.
 *
 * Every variant carries `run_id`, `thread_id`, and a `timestamp` so that
 * frontend consumers can always route and order events.
 */
export type RuntimeEvent = { "kind": "RunStarted", "data": { 
/**
 * Run that started.
 */
run: AgentRun, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "RunStatusChanged", "data": { 
/**
 * Run that changed status.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * New status.
 */
status: AgentRunStatus, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "MessageDelta", "data": { 
/**
 * Run producing the message.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * New content fragment.
 */
content: string, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "MessageCompleted", "data": { 
/**
 * Run producing the message.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Full assembled message content.
 */
content: string, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "ToolRequested", "data": { 
/**
 * Run requesting the tool.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Tool name.
 */
tool_name: string, 
/**
 * Tool arguments.
 */
arguments: any, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "ToolApprovalRequired", "data": { 
/**
 * Run requesting approval.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Approval request id.
 */
request_id: bigint, 
/**
 * Action to approve.
 */
action: string, 
/**
 * Resource targeted by the action.
 */
resource: string, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "ToolStarted", "data": { 
/**
 * Run executing the tool.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Tool name.
 */
tool_name: string, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "ToolCompleted", "data": { 
/**
 * Run executing the tool.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Tool name.
 */
tool_name: string, 
/**
 * Tool result payload.
 */
result: any, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "ToolFailed", "data": { 
/**
 * Run executing the tool.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Tool name.
 */
tool_name: string, 
/**
 * Error message.
 */
error: string, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "ArtifactCreated", "data": { 
/**
 * Run that created the artifact.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Artifact metadata.
 */
artifact: Artifact, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "RunFailed", "data": { 
/**
 * Run that failed.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Error message.
 */
error: string, 
/**
 * Timestamp of the event.
 */
timestamp: string, } } | { "kind": "RunCompleted", "data": { 
/**
 * Run that completed.
 */
run_id: AgentRunId, 
/**
 * Thread that owns the run.
 */
thread_id: ThreadId, 
/**
 * Timestamp of the event.
 */
timestamp: string, } };
